import Head from "next/head";
import { Inter } from "next/font/google";
import ConnectButton from "@/lib/components/ConnectButton";
import useActiveAccount from "@/lib/hooks/useActiveAccount";
import { formatAddress } from "@/lib/utils/format";
import useAutoConnect from "@/lib/hooks/useAutoConnect";
import useChainId from "@/lib/hooks/useChainId";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useAutoConnect();
  const account = useActiveAccount();

  return (
    <>
      <Head>
        <title>Wallet Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <ConnectButton />
        <p>Address: {formatAddress(account?.address ?? '')}</p>
      </main>
    </>
  );
}
